import type { BrowserContextOptions, Page } from "@playwright/test";
import { TEST_PASSCODE } from "./constants.ts";
import { expect, screenshotPath, test } from "./fixtures.ts";

// __TITLE__ against the real room server, in throwaway worlds. Generated by `pnpm new-game`;
// grow these tests with the game.

const freshWorld = () => `t${Math.random().toString(36).slice(2, 10)}`;

interface Hook {
  frames?: number;
  state(): { total: number; players: Record<string, { taps: number }> };
  dispatch(name: string, input: unknown): Promise<{ ok: boolean; error?: string }>;
  sheepOnScreen(): { x: number; y: number };
}

async function open(page: Page, as: string, world: string) {
  await page.goto(`/games/__NAME__/?as=${as}&world=${world}&autostart`);
  await page.waitForFunction(
    () =>
      ((window.__game?.frames as number | undefined) ?? 0) > 20 &&
      window.__game?.sheepOnScreen !== undefined,
  );
}

test("__TITLE__: tapping the sheep counts for everyone", async ({ page, browser }, info) => {
  test.slow();
  const world = freshWorld();
  await open(page, "kid1", world);

  const sheep = await page.evaluate(() => (window.__game as unknown as Hook).sheepOnScreen());
  if (info.project.use.hasTouch) await page.touchscreen.tap(sheep.x, sheep.y);
  else await page.mouse.click(sheep.x, sheep.y);
  await expect(page.getByTestId("total")).toContainText("1");
  await page.screenshot({ path: screenshotPath("__NAME__", info.project.name) });

  // A second family member on another device joins the same world.
  const context = await browser.newContext(info.project.use as BrowserContextOptions);
  const other = await context.newPage();
  await other.request.post("/login", {
    form: { passcode: TEST_PASSCODE, next: "/" },
    maxRedirects: 0,
  });
  await open(other, "grownup", world);
  await expect(page.getByTestId("online")).toContainText("🦊");
  const result = await other.evaluate(() => (window.__game as unknown as Hook).dispatch("tap", {}));
  expect(result.ok).toBe(true);
  await expect(page.getByTestId("total")).toContainText("2");
  await context.close();
});

test("__TITLE__: opened without a profile, it goes through the picker and back", async ({
  page,
}) => {
  await page.goto(`/games/__NAME__/?world=${freshWorld()}`);
  await expect(page.getByTestId("picker")).toBeVisible();
  await page.getByTestId("pick-kid1").click();
  await page.waitForURL(/\/games\/__NAME__\//);
  await expect(page.getByTestId("title-screen")).toBeVisible();
});
